---
name: Check (Ruff)

on:
  push:
    branches:
      - main
      - test

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
