---
name: Test (Run Create My New Project)

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test run the create new project script
        run: python create_my_new_project.py "my dank app"

      - name: Run image
        uses: abatilo/actions-poetry@v2

      - name: Configure Poetry to install dependencies in virtualenv
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        working-directory: ../mydankapp
        run: poetry install --without dev

      - name: Test with pytest
        working-directory: ../mydankapp
        run: .venv/bin/pytest # No code coverage for this one
