---
name: main

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2

      - name: Configure Poetry to install dependencies in virtualenv
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install --without dev

      - name: Test with pytest
        # run: .venv/bin/pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
        run: .venv/bin/pytest --doctest-modules --cov=com
