---
name: Test

on:
  push:
    branches:
      - main
      - test
    paths-ignore:
      - "**/README*"
      - ".github/workflows/check.yml"
      - ".github/workflows/check_types.yml"

jobs:
  test_boilerplate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Don't bother with beta versions, slow on github. https://github.com/actions/python-versions/releases
        # Normally this has multiple versions but python 3.14 changed how type hints work. Future version will be added to the list.
        python-version: ["3.14"]
    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --group test

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install frontend dependencies, build frountend
        run: |
          bun install --frozen-lockfile
          bun run codegen && bun run build

      - name: Test with pytest
        run: |
          .venv/bin/coverage run
          .venv/bin/coverage xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
